version: "2"
services:
  client:
    env_file: ./client/.env
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    env_file: ./server/.env
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
